In [ ]:
# SNP array的数据进行可视化

## read PED data from PLINK

In [ ]:
import pandas as pd
import polars as pl
import os
import sys
import numpy as np
from pathlib import Path

In [27]:
data_root = r"D:\03.projects\AI.PGT\data\pengjingjing\SNP_result\pengjingjign_203368710006"
ped_file = Path(os.path.join(data_root, "PLINK_241025_0935", "pengjingjign_203368710006.ped"))
map_file = Path(os.path.join(data_root, "PLINK_241025_0935", "pengjingjign_203368710006.map"))

ped_df = pd.read_csv(ped_file, sep="\t", header=None)
map_df = pd.read_csv(map_file, sep="\t", header=None)

# show
# print(ped_df.iloc[:, :10].head())

C:\Users\kuisu\AppData\Local\Temp\ipykernel_39404\2703771030.py:5: DtypeWarning: Columns (1896,1897,1898,1899,1902,1903,1908,1909,1914,1915,1922,1923,1924,1925,1926,1927,1928,1929,1936,1937,1938,1939,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1968,1969,1974,1975,1976,1977,1978,1979,1984,1985,1986,1987,1990,1991,1992,1993,1994,1995,1996,1997,2002,2003,2004,2005,2012,2013,2014,2015,2018,2019,2020,2021,2024,2025,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2042,2043,2044,2045,2050,2051,2058,2059,2060,2061,2074,2075,2076,2077,2078,2079,2084,2085,2086,2087,2088,2089,2092,2093,2094,2095,2098,2099,2104,2105,2106,2107,2112,2113,2114,2115,2118,2119,2130,2131,2132,2133,2134,2135,2136,2137,2138,2139,2140,2141,2150,2151,2156,2157,2170,2171,2174,2175,2176,2177,2182,2183,2186,2187,2188,2189,2190,2191,2192,2193,2202,2203,2204,2205,2218,2219,2224,2225,2226,2227,2234,2235,2238,2239,2250,2251,2252,2253,2262,2263,2266,2267,2272,2273,2274,2275,2278,2279,2286,2287,2288,2289,2290,2291,2294,2295,2296,2297,2306,2307,2308,2309,2310,2311,2312,2313,2314,2315,2318,2319,2320,2321,2322,2323,2324,2325,2328,2329,2332,2333,2336,2337,2338,2339,2340,2341,2342,2343,2344,2345,2354,2355,2356,2357,2360,2361,2364,2365,2366,2367,2368,2369,2370,2371,2372,2373,2374,2375,2380,2381,2384,2385,2386,2387,2388,2389,2394,2395,2396,2397,2398,2399,2402,2403,2404,2405,2406,2407,2408,2409,2410,2411,2416,2417,2418,2419,2420,2421,2422,2423,2428,2429,2438,2439,2450,2451,2454,2455,2466,2467,2468,2469,2470,2471,2476,2477,2478,2479,2482,2483,2488,2489,2506,2507,2508,2509,2510,2511,2512,2513,2522,2523,2540,2541,2542,2543,2546,2547,2556,2557,2558,2559,2560,2561,2566,2567,2570,2571,2572,2573,2574,2575,2578,2579,2588,2589,2590,2591,2592,2593,2598,2599,2600,2601,2602,2603,2606,2607,2608,2609,2610,2611,2614,2615,2616,2617,2618,2619,2634,2635,2636,2637,2640,2641,2644,2645,2648,2649,2652,2653,2656,2657,2658,2659,2660,2661,2662,2663,2664,2665,2666,2667,2670,2671,2672,2673,2674,2675,2676,2677,2682,2683,2692,2693,2694,2695,2696,2697,2698,2699,2700,2701,2702,2703,2708,2709,2710,2711,2718,2719,2720,2721,2726,2727,2730,2731,2732,2733,2736,2737,2738,2739,2740,2741,2742,2743,2744,2745,2746,2747,2752,2753,2756,2757,2758,2759,2762,2763,2766,2767,2772,2773,2774,2775,2776,2777,2778,2779,2786,2787,2794,2795,2798,2799,2800,2801,2802,2803,2804,2805,2808,2809,2812,2813,2818,2819,2820,2821,2822,2823,2830,2831,2836,2837,2846,2847,2850,2851,2854,2855,2862,2863,2864,2865,2866,2867,2870,2871,2874,2875,2880,2881,2884,2885,2888,2889,2900,2901,2904,2905,2906,2907,2908,2909,2910,2911,2920,2921,2922,2923,2926,2927,2928,2929,2934,2935,2936,2937,2940,2941,2942,2943,2944,2945,2946,2947,2948,2949,2950,2951,2952,2953,2958,2959,2966,2967,2978,2979,2986,2987,2988,2989,2992,2993,3000,3001,3004,3005,3006,3007,3008,3009,3014,3015,3016,3017,3018,3019,3022,3023,3024,3025,3026,3027,3030,3031,3034,3035,3036,3037,3038,3039,3044,3045,3046,3047,3048,3049,3054,3055,3056,3057,3060,3061,3062,3063,3068,3069,3070,3071,3072,3073,3080,3081,3086,3087,3090,3091,3092,3093,3094,3095,3096,3097,3100,3101,3102,3103,3104,3105,3106,3107,3108,3109,3112,3113,3114,3115,3118,3119,3120,3121,3132,3133,3138,3139,3140,3141,3144,3145,3152,3153,3156,3157,3158,3159,3160,3161,3162,3163,3176,3177,3180,3181,3182,3183,3184,3185,3188,3189,3190,3191,3192,3193,3200,3201,3202,3203,3204,3205,3210,3211,3212,3213,3214,3215,3218,3219,3220,3221,3228,3229,3230,3231,3240,3241,3244,3245,3246,3247,3254,3255,3256,3257,3258,3259,3260,3261,3262,3263,3266,3267,3268,3269,3270,3271,3274,3275,3278,3279,3282,3283,3284,3285,3286,3287,3288,3289,3294,3295,3298,3299,3302,3303,3304,3305,3308,3309,3312,3313,3314,3315,3316,3317,3320,3321,3324,3325,3326,3327,3334,3335,3338,3339,3340,3341,3348,3349,3368,3369,3372,3373,3378,3379,3382,3383,3388,3389,3392,3393,3396,3397,3408,3409,3414,3415,3416,3417,3418,3419,3424,3425,3426,3427,3428,3429,3442,3443,3448,3449,3452,3453,3456,3457,3458,3459,3460,3461,3462,3463,3466,3467,3468,3469,3472,3473,3474,3475,3476,3477,3478,3479,3480,3481,3482,3483,3484,3485,3486,3487,3488,3489,3492,3493,3494,3495,3496,3497,3500,3501,3506,3507,3514,3515,3518,3519,3520,3521,3522,3523,3524,3525,3528,3529,3532,3533,3536,3537,3538,3539,3544,3545,3548,3549,3552,3553,3556,3557,3558,3559,3560,3561,3562,3563,3564,3565,3570,3571,3574,3575,3576,3577,3584,3585,3586,3587,3592,3593,3594,3595,3596,3597,3598,3599,3604,3605,3606,3607,3608,3609,3614,3615,3616,3617,3624,3625,3636,3637,3640,3641,3652,3653,3654,3655,3666,3667,3668,3669,3670,3671,3672,3673,3680,3681,3692,3693,3694,3695,3698,3699,3700,3701,3704,3705,3706,3707,3708,3709,3710,3711,3714,3715,3718,3719,3720,3721,3722,3723,3724,3725,3726,3727,3730,3731,3732,3733,3740,3741,3748,3749,3750,3751,3754,3755,3758,3759,3764,3765,3766,3767,3770,3771,3776,3777,3778,3779,3784,3785,3798,3799,3800,3801,3802,3803,3804,3805,3812,3813,3814,3815,3816,3817,3818,3819,3820,3821,3822,3823,3826,3827,3832,3833,3834,3835,3836,3837,3840,3841,3850,3851,3852,3853,3858,3859,3864,3865,3870,3871,3892,3893,3896,3897,3898,3899,3900,3901,3904,3905,3914,3915,3916,3917,3918,3919,3924,3925,3930,3931,3932,3933,3934,3935,3940,3941,3946,3947,3954,3955,3956,3957,3960,3961,3968,3969,3970,3971,3972,3973,3974,3975,3976,3977,3978,3979,3980,3981,3982,3983,3988,3989,3990,3991,3994,3995,4000,4001,4004,4005,4006,4007,4008,4009,4010,4011,4014,4015,4016,4017,4018,4019,4034,4035,4036,4037,4048,4049,4052,4053,4054,4055,4060,4061,4068,4069,4074,4075,4076,4077,4080,4081,4082,4083,4094,4095,4098,4099,4100,4101,4102,4103,4104,4105,4112,4113,4116,4117,4118,4119,4126,4127,4130,4131,4138,4139,4140,4141,4142,4143,4146,4147,4148,4149,4150,4151,4152,4153,4158,4159,4164,4165,4166,4167,4170,4171,4172,4173,4176,4177,4178,4179,4182,4183,4190,4191,4196,4197,4202,4203,4204,4205,4210,4211,4218,4219,4220,4221,4222,4223,4228,4229,4232,4233,4234,4235,4236,4237,4238,4239,4240,4241,4242,4243,4250,4251,4252,4253,4268,4269,4270,4271,4276,4277,4278,4279,4284,4285,4294,4295,4298,4299,4302,4303,4304,4305,4306,4307,4308,4309,4310,4311,4312,4313,4320,4321,4324,4325,4326,4327,4334,4335,4346,4347,4354,4355,4358,4359,4360,4361,4364,4365,4368,4369,4370,4371,4376,4377,4382,4383,4384,4385,4386,4387,4388,4389,4390,4391,4392,4393,4394,4395,4398,4399,4400,4401,4402,4403,4406,4407,4408,4409,4412,4413,4414,4415,4416,4417,4430,4431,4434,4435,4438,4439,4442,4443,4444,4445,4446,4447,4450,4451,4452,4453,4456,4457,4458,4459,4460,4461,4462,4463,4464,4465,4468,4469,4470,4471,4472,4473,4474,4475,4478,4479,4480,4481,4484,4485,4486,4487,4488,4489,4490,4491,4496,4497,4502,4503,4506,4507,4508,4509,4514,4515,4516,4517,4518,4519,4522,4523,4526,4527,4534,4535,4536,4537,4538,4539,4540,4541,4546,4547,4550,4551,4552,4553,4554,4555,4560,4561,4562,4563,4566,4567,4568,4569,4570,4571,4572,4573,4576,4577,4582,4583,4586,4587,4590,4591,4592,4593,4598,4599,4600,4601,4602,4603,4604,4605,4606,4607,4608,4609,4612,4613,4614,4615,4624,4625,4626,4627,4630,4631,4632,4633,4636,4637,4644,4645,4648,4649,4668,4669,4670,4671,4676,4677,4678,4679,4684,4685,4690,4691,4692,4693,4694,4695,4696,4697,4700,4701,4704,4705,4710,4711,4712,4713,4714,4715,4720,4721,4722,4723,4736,4737,4742,4743,4746,4747,4748,4749,4750,4751,4754,4755,4758,4759,4762,4763,4764,4765,4766,4767,4768,4769,4770,4771,4774,4775,4780,4781,4784,4785,4786,4787,4788,4789,4792,4793,4804,4805,4806,4807,4808,4809,4816,4817,4820,4821,4822,4823,4824,4825,4826,4827,4828,4829,4832,4833,4840,4841,4842,4843,4846,4847,4850,4851,4854,4855,4856,4857,4858,4859,4860,4861,4864,4865,4866,4867,4872,4873,4874,4875,4878,4879,4882,4883,4890,4891,4892,4893,4894,4895,4900,4901,4902,4903,4906,4907,4908,4909,4910,4911,4912,4913,4916,4917,4920,4921,4922,4923,4926,4927,4930,4931,4936,4937,4940,4941,4944,4945,4946,4947,4948,4949,4954,4955,4960,4961,4962,4963,4972,4973,4978,4979,4982,4983,4984,4985,4988,4989,4992,4993,4996,4997,4998,4999,5000,5001,5004,5005,5008,5009,5012,5013,5014,5015,5022,5023,5026,5027,5036,5037,5038,5039,5044,5045,5046,5047,5056,5057,5058,5059,5062,5063,5066,5067,5070,5071,5072,5073,5074,5075,5078,5079,5090,5091,5092,5093,5094,5095,5098,5099,5104,5105,5106,5107,5108,5109,5112,5113,5116,5117,5118,5119,5124,5125,5128,5129,5132,5133,5136,5137,5138,5139,5142,5143,5150,5151,5152,5153,5154,5155,5160,5161,5164,5165,5172,5173,5174,5175,5176,5177,5178,5179,5182,5183,5188,5189,5198,5199,5202,5203,5210,5211,5212,5213,5216,5217,5218,5219,5222,5223,5230,5231,5232,5233,5236,5237,5240,5241,5242,5243,5248,5249,5250,5251,5252,5253,5254,5255,5260,5261,5262,5263,5264,5265,5268,5269,5274,5275,5278,5279,5280,5281,5282,5283,5290,5291,5294,5295,5296,5297,5300,5301,5302,5303,5306,5307,5312,5313,5322,5323,5324,5325,5330,5331,5332,5333,5334,5335,5338,5339,5350,5351,5352,5353,5360,5361,5362,5363,5366,5367,5374,5375,5376,5377,5382,5383,5384,5385,5386,5387,5390,5391,5400,5401,5402,5403,5404,5405,5410,5411,5416,5417,5418,5419,5422,5423,5424,5425,5430,5431,5438,5439,5440,5441,5446,5447,5450,5451,5456,5457,5458,5459,5462,5463,5468,5469,5478,5479,5480,5481,5492,5493,5506,5507,5508,5509,5512,5513,5514,5515,5522,5523,5524,5525,5540,5541,5542,5543,5544,5545,5556,5557,5558,5559,5566,5567,5568,5569,5572,5573,5578,5579,5580,5581,5582,5583,5586,5587,5588,5589,5590,5591,5608,5609,5632,5633,5638,5639,5640,5641,5644,5645,5650,5651,5658,5659,5660,5661,5662,5663,5664,5665,5666,5667,5670,5671,5672,5673,5678,5679,5680,5681,5684,5685,5688,5689,5692,5693,5696,5697,5700,5701,5708,5709,5710,5711,5712,5713,5718,5719,5720,5721,5722,5723,5734,5735,5740,5741,5744,5745,5746,5747,5752,5753,5758,5759,5760,5761,5764,5765,5768,5769,5770,5771,5776,5777,5778,5779,5788,5789,5794,5795,5796,5797,5798,5799,5812,5813,5814,5815,5820,5821,5822,5823,5824,5825,5828,5829,5830,5831,5836,5837,5838,5839,5842,5843,5846,5847,5852,5853,5854,5855,5856,5857,5862,5863,5864,5865,5866,5867,5870,5871,5872,5873,5876,5877,5878,5879,5886,5887,5890,5891,5900,5901,5904,5905,5906,5907,5910,5911,5912,5913,5920,5921,5922,5923,5924,5925,5926,5927,5930,5931,5932,5933,5940,5941,5944,5945,5954,5955,5956,5957,5958,5959,5960,5961,5962,5963,5964,5965,5966,5967,5968,5969,5970,5971,5976,5977,5984,5985,5986,5987,5990,5991,5992,5993,5994,5995,5996,5997,5998,5999,6000,6001,6004,6005,6006,6007,6008,6009,6010,6011,6018,6019,6026,6027,6028,6029,6034,6035,6036,6037,6038,6039,6042,6043,6046,6047,6048,6049,6050,6051,6052,6053,6056,6057,6060,6061,6062,6063,6066,6067,6072,6073,6074,6075,6082,6083,6084,6085,6086,6087,6088,6089,6090,6091,6098,6099,6100,6101,6102,6103,6104,6105,6106,6107,6108,6109,6112,6113,6118,6119,6120,6121,6122,6123,6126,6127,6128,6129,6132,6133,6136,6137,6140,6141,6146,6147,6148,6149,6152,6153,6160,6161,6164,6165,6172,6173,6178,6179,6188,6189,6194,6195,6198,6199,6204,6205,6206,6207,6210,6211,6212,6213,6226,6227,6230,6231,6232,6233,6236,6237,6238,6239,6242,6243,6250,6251,6256,6257,6260,6261,6266,6267,6270,6271,6272,6273,6274,6275,6276,6277,6280,6281,6284,6285,6290,6291,6292,6293,6294,6295,6296,6297,6298,6299,6302,6303,6306,6307,6310,6311,6312,6313,6318,6319,6320,6321,6324,6325,6330,6331,6332,6333,6348,6349,6360,6361,6364,6365,6366,6367,6372,6373,6378,6379,6380,6381,6382,6383,6384,6385,6394,6395,6400,6401,6404,6405,6406,6407,6408,6409,6412,6413,6414,6415,6416,6417,6422,6423,6424,6425,6430,6431,6432,6433,6434,6435,6442,6443,6444,6445,6448,6449,6450,6451,6454,6455,6462,6463,6464,6465,6474,6475,6484,6485,6486,6487,6488,6489,6490,6491,6492,6493,6494,6495,6498,6499,6504,6505,6510,6511,6512,6513,6516,6517,6518,6519,6524,6525,6528,6529,6534,6535,6538,6539,6550,6551,6554,6555,6556,6557,6558,6559,6560,6561,6566,6567,6572,6573,6574,6575,6576,6577,6582,6583,6584,6585,6588,6589,6592,6593,6596,6597,6600,6601,6602,6603,6608,6609,6612,6613,6614,6615,6616,6617,6622,6623,6624,6625,6626,6627,6628,6629,6630,6631,6634,6635,6638,6639,6642,6643,6648,6649,6650,6651,6654,6655,6658,6659,6660,6661,6662,6663,6664,6665,6670,6671,6676,6677,6690,6691,6692,6693,6694,6695,6696,6697,6698,6699,6700,6701,6702,6703,6704,6705,6708,6709,6714,6715,6716,6717,6726,6727,6730,6731,6734,6735,6736,6737,6742,6743,6746,6747,6750,6751,6754,6755,6756,6757,6764,6765,6766,6767,6768,6769,6770,6771,6772,6773,6774,6775,6776,6777,6778,6779,6788,6789,6792,6793,6794,6795,6796,6797,6804,6805,6806,6807,6808,6809,6812,6813,6818,6819,6820,6821,6822,6823,6824,6825,6826,6827,6828,6829,6840,6841,6842,6843,6846,6847,6852,6853,6858,6859,6860,6861,6868,6869,6872,6873,6874,6875,6880,6881,6882,6883,6884,6885,6888,6889,6894,6895,6896,6897,6900,6901,6902,6903,6904,6905,6906,6907,6908,6909,6916,6917,6920,6921,6922,6923,6926,6927,6938,6939,6944,6945,6950,6951,6952,6953,6956,6957,6962,6963,6964,6965,6966,6967,6968,6969,6974,6975,6980,6981,6986,6987,6992,6993,6994,6995,6998,6999,7004,7005,7006,7007,7014,7015,7016,7017,7018,7019,7026,7027,7032,7033,7034,7035,7036,7037,7038,7039,7040,7041,7044,7045,7046,7047,7048,7049,7054,7055,7056,7057,7058,7059,7062,7063,7070,7071,7072,7073,7074,7075,7076,7077,7078,7079,7080,7081,7084,7085,7088,7089,7090,7091,7094,7095,7096,7097,7100,7101,7106,7107,7110,7111,7118,7119,7120,7121,7122,7123,7126,7127,7130,7131,7136,7137,7138,7139,7140,7141,7142,7143,7152,7153,7156,7157,7158,7159,7164,7165,7166,7167,7170,7171,7172,7173,7178,7179,7180,7181,7184,7185,7192,7193,7196,7197,7198,7199,7206,7207,7212,7213,7216,7217,7218,7219,7220,7221,7222,7223,7228,7229,7230,7231,7234,7235,7236,7237,7246,7247,7248,7249,7252,7253,7256,7257,7262,7263,7264,7265,7272,7273,7278,7279,7282,7283,7284,7285,7286,7287,7290,7291,7292,7293,7296,7297,7298,7299,7300,7301,7302,7303,7304,7305,7310,7311,7312,7313,7314,7315,7316,7317,7320,7321,7322,7323,7328,7329,7330,7331,7332,7333,7336,7337,7338,7339,7340,7341,7344,7345,7346,7347,7356,7357,7358,7359,7360,7361,7362,7363,7368,7369,7372,7373,7374,7375,7382,7383,7384,7385,7388,7389,7390,7391,7394,7395,7402,7403,7404,7405,7406,7407,7410,7411,7416,7417,7424,7425,7426,7427,7434,7435,7438,7439,7440,7441,7442,7443,7448,7449,7452,7453,7454,7455,7456,7457,7462,7463,7468,7469,7474,7475,7482,7483,7492,7493,7494,7495,7498,7499,7500,7501,7502,7503,7504,7505,7506,7507,7508,7509,7510,7511,7512,7513,7516,7517,7522,7523,7530,7531,7540,7541,7548,7549,7558,7559,7560,7561,7572,7573,7578,7579,7582,7583,7588,7589,7590,7591,7596,7597,7600,7601,7602,7603,7610,7611,7612,7613,7618,7619,7620,7621,7628,7629,7630,7631,7632,7633,7634,7635,7638,7639,7646,7647,7648,7649,7656,7657,7660,7661,7662,7663,7666,7667,7668,7669,7676,7677,7680,7681,7682,7683,7684,7685,7686,7687,7688,7689,7694,7695,7696,7697,7698,7699,7702,7703,7704,7705,7706,7707,7708,7709,7714,7715,7716,7717,7718,7719,7724,7725,7732,7733,7734,7735,7736,7737,7738,7739,7750,7751,7756,7757,7760,7761,7766,7767,7774,7775,7776,7777,7778,7779,7782,7783,7784,7785,7786,7787,7792,7793,7798,7799,7802,7803,7812,7813,7816,7817,7818,7819,7820,7821,7822,7823,7824,7825,7830,7831,7832,7833,7836,7837,7838,7839,7840,7841,7842,7843,7852,7853,7856,7857,7862,7863,7864,7865,7870,7871,7872,7873,7878,7879,7884,7885,7886,7887,7892,7893,7898,7899,7908,7909,7910,7911,7914,7915,7928,7929,7934,7935,7936,7937,7938,7939,7942,7943,7944,7945,7946,7947,7956,7957,7964,7965,7966,7967,7968,7969,7970,7971,7976,7977,7978,7979,7982,7983,7984,7985,7986,7987,7988,7989,7990,7991,7992,7993,7996,7997,7998,7999,8000,8001,8006,8007,8008,8009,8014,8015,8016,8017,8022,8023,8024,8025,8026,8027,8028,8029,8030,8031,8032,8033,8044,8045,8048,8049,8052,8053,8056,8057,8058,8059,8066,8067,8070,8071,8072,8073,8076,8077,8080,8081,8084,8085,8088,8089,8098,8099,8104,8105,8106,8107,8108,8109,8116,8117,8118,8119,8120,8121,8122,8123,8126,8127,8128,8129,8132,8133,8138,8139,8162,8163,8164,8165,8166,8167,8174,8175,8176,8177,8180,8181,8182,8183,8184,8185,8190,8191,8192,8193,8196,8197,8200,8201,8202,8203,8204,8205,8206,8207,8208,8209,8210,8211,8216,8217,8218,8219,8220,8221,8222,8223,8224,8225,8230,8231,8236,8237,8242,8243,8246,8247,8254,8255,8262,8263,8266,8267,8268,8269,8274,8275,8286,8287,8288,8289,8298,8299,8306,8307,8310,8311,8314,8315,8318,8319,8322,8323,8324,8325,8328,8329,8334,8335,8340,8341,8344,8345,8346,8347,8356,8357,8364,8365,8368,8369,8372,8373,8374,8375,8376,8377,8378,8379,8382,8383,8386,8387,8388,8389,8396,8397,8398,8399,8402,8403,8408,8409,8412,8413,8434,8435,8436,8437,8438,8439,8440,8441,8442,8443,8446,8447,8452,8453,8456,8457,8462,8463,8466,8467,8474,8475,8476,8477,8478,8479,8480,8481,8482,8483,8484,8485,8486,8487,8490,8491,8498,8499,8506,8507,8510,8511,8512,8513,8514,8515,8518,8519,8520,8521,8522,8523,8528,8529,8530,8531,8532,8533,8534,8535,8540,8541,8542,8543,8546,8547,8548,8549,8560,8561,8564,8565,8566,8567,8568,8569,8570,8571,8572,8573,8578,8579,8586,8587,8588,8589,8590,8591,8594,8595,8606,8607,8608,8609,8612,8613,8620,8621,8624,8625,8630,8631,8632,8633,8634,8635,8640,8641,8646,8647,8648,8649,8656,8657,8666,8667,8678,8679,8682,8683,8686,8687,8688,8689,8692,8693,8696,8697,8700,8701,8702,8703,8708,8709,8716,8717,8718,8719,8728,8729,8730,8731,8734,8735,8738,8739,8740,8741,8744,8745,8746,8747,8752,8753,8758,8759,8764,8765,8770,8771,8778,8779,8780,8781,8782,8783,8784,8785,8792,8793,8796,8797,8798,8799,8800,8801,8802,8803,8804,8805,8808,8809,8822,8823,8830,8831,8832,8833,8836,8837,8844,8845,8848,8849,8850,8851,8852,8853,8854,8855,8856,8857,8858,8859,8866,8867,8872,8873,8874,8875,8878,8879,8884,8885,8888,8889,8890,8891,8896,8897,8898,8899,8910,8911,8916,8917,8918,8919,8920,8921,8922,8923,8924,8925,8930,8931,8932,8933,8934,8935,8938,8939,8940,8941,8946,8947,8950,8951,8954,8955,8958,8959,8968,8969,8972,8973,8974,8975,8982,8983,8984,8985,8986,8987,8988,8989,8990,8991,8992,8993,8996,8997,9008,9009,9014,9015,9018,9019,9020,9021,9022,9023,9026,9027,9028,9029,9030,9031,9032,9033,9034,9035,9040,9041,9044,9045,9052,9053,9054,9055,9056,9057,9064,9065,9070,9071,9086,9087,9102,9103,9104,9105,9106,9107,9108,9109,9110,9111,9116,9117,9122,9123,9128,9129,9134,9135,9136,9137,9140,9141,9146,9147,9148,9149,9150,9151,9152,9153,9154,9155,9156,9157,9158,9159,9160,9161,9166,9167,9168,9169,9170,9171,9172,9173,9176,9177,9180,9181,9186,9187,9188,9189,9200,9201,9204,9205,9206,9207,9208,9209,9210,9211,9216,9217,9218,9219,9220,9221,9222,9223,9224,9225,9226,9227,9234,9235,9236,9237,9248,9249,9254,9255,9256,9257,9262,9263,9274,9275,9276,9277,9280,9281,9284,9285,9288,9289,9290,9291,9292,9293,9296,9297,9302,9303,9318,9319,9326,9327,9332,9333,9334,9335,9336,9337,9338,9339,9340,9341,9346,9347,9356,9357,9358,9359,9368,9369,9370,9371,9372,9373,9378,9379,9380,9381,9382,9383,9384,9385,9388,9389,9398,9399,9402,9403,9404,9405,9406,9407,9408,9409,9410,9411,9420,9421,9422,9423,9424,9425,9428,9429,9432,9433,9438,9439,9440,9441,9442,9443,9444,9445,9446,9447,9448,9449,9450,9451,9456,9457,9460,9461,9462,9463,9464,9465,9468,9469,9470,9471,9480,9481,9484,9485,9492,9493,9494,9495,9504,9505,9508,9509,9510,9511,9512,9513,9514,9515,9516,9517,9524,9525,9530,9531,9532,9533,9534,9535,9536,9537,9540,9541,9544,9545,9548,9549,9554,9555,9562,9563,9570,9571,9578,9579,9580,9581,9582,9583,9584,9585,9590,9591,9592,9593,9594,9595,9596,9597,9598,9599,9600,9601,9604,9605,9608,9609,9610,9611,9612,9613,9614,9615,9616,9617,9620,9621,9622,9623,9624,9625,9632,9633,9634,9635,9640,9641,9642,9643,9646,9647,9648,9649,9650,9651,9652,9653,9654,9655,9662,9663,9664,9665,9668,9669,9670,9671,9678,9679,9682,9683,9686,9687,9688,9689,9692,9693,9694,9695,9696,9697,9698,9699,9706,9707,9710,9711,9712,9713,9714,9715,9718,9719,9720,9721,9726,9727,9728,9729,9732,9733,9736,9737,9740,9741,9744,9745,9746,9747,9750,9751,9752,9753,9754,9755,9762,9763,9766,9767,9770,9771,9772,9773,9774,9775,9782,9783,9784,9785,9786,9787,9788,9789,9790,9791,9792,9793,9798,9799,9800,9801,9812,9813,9818,9819,9820,9821,9826,9827,9828,9829,9830,9831,9836,9837,9840,9841,9842,9843,9850,9851,9852,9853,9856,9857,9860,9861,9864,9865,9868,9869,9870,9871,9872,9873,9874,9875,9878,9879,9880,9881,9882,9883,9886,9887,9888,9889,9890,9891,9894,9895,9896,9897,9898,9899,9902,9903,9904,9905,9908,9909,9912,9913,9918,9919,9920,9921,9922,9923,9924,9925,9928,9929,9934,9935,9940,9941,9942,9943,9946,9947,9952,9953,9954,9955,9956,9957,9962,9963,9966,9967,9970,9971,9972,9973,9974,9975,9978,9979,9986,9987,9988,9989,9994,9995,

In [33]:
# map file
print(map_df.head())
print(f"map file shape: {map_df.shape}")

    0            1          2          3
0  13  cnvi0111185   94.29845  100631779
1   2  cnvi0111186  183.42660  177058958
2  17  cnvi0111187   65.07668   35295593
3   8  cnvi0111188   76.01000   65499402
4   2  cnvi0111189  183.42960  177061178
map file shape: (298563, 4)

In [34]:
# ped file
# 298563 SNPs, 每个SNP两个基因型 + 5列前缀信息
print(pd.concat([ped_df.iloc[:, :5], ped_df.iloc[:, -5:]], axis=1).head())
print(f"ped file shape: {ped_df.shape}")

   0                    1       2       3       4      597127 597128 597129  \
0       1  203368710006_R01C01       0       0       0      C      G      G
1       2  203368710006_R01C02       0       0       0      C      G      G
2       3  203368710006_R02C01       0       0       0      C      G      G
3       4  203368710006_R02C02       0       0       0      C      G      G
4       5  203368710006_R03C01       0       0       0      C      G      G

  597130 597131
0      A      A
1      A      A
2      A      A
3      A      A
4      A      A
ped file shape: (12, 597132)

In [35]:
print(298563 * 2 + 5)

597131

## SNP Array Data
- 读取Experiment表格
- 逐行读取，将其拼接为一个表格
- 按group的方式进行，使用dict方式按照实验组进行存储

In [36]:
import pandas as pd
import os

In [85]:
data_path=r"D:\03.projects\AI.PGT\snparray_analysis\data\experiment_snparray.csv"

with open(data_path, 'r') as file:
    lines = file.readlines()

experiments = []
experiment_dict = {}
chip_line = -1
for line in lines:
    # get experiment time
    line_data = [i.strip() for i in line.strip().split(",")]
    if "实验时间" in line:
        chip_line = 0
        if experiment_dict:
            experiments.append(experiment_dict)
            experiment_dict = {}
        time_key, time_value = line_data[1].split("：")
        experiment_dict[time_key.strip()] = time_value.strip().replace(" ", "")
        experimenter_key, experimenter_value = line_data[7].split("：")
        experiment_dict[experimenter_key.strip()] = experimenter_value.strip()
    elif "备注" in line:
        comment_key, comment_value = line_data[0][:2].strip(), line_data[0][3:].strip()
        experiment_dict[comment_key.strip()] = comment_value.strip()
        chip_line += 1

    if chip_line in [0, 3]:
        chip_line += 1
        continue

    if chip_line >= 1 and chip_line <= 5:
        experiment_dict[f"chip_num_{chip_line}"] = line_data
        chip_line += 1
    elif chip_line == 6:
        X1_key, X1_value = line_data[1].split("：")
        experiment_dict[X1_key.strip()] = X1_value.strip().replace(" ", "")
        X2_key, X2_value = line_data[7].split("：")
        experiment_dict[X2_key.strip()] = X2_value.strip()
        chip_line += 1
    elif chip_line == 7:
        X3_key, X3_value = line_data[1].split("：")
        experiment_dict[X3_key.strip()] = X3_value.strip().replace(" ", "")
        X4_key, X4_value = line_data[7].split("：")
        experiment_dict[X4_key.strip()] = X4_value.strip()
        chip_line += 1

print(len(experiments))
print(experiments[0])

9
{'实验时间': '2019年3月28日', '数据分析': '郭婧', 'chip_num_1': ['Cyto-12', 'F-徐锦荣', '柯奕K1', 'K2', 'K3', 'K4', 'K5', 'K6', 'K7', 'K8', 'K9', '梁健美L2', 'RB', ''], 'chip_num_2': ['Cyto-12', 'M-罗丽贞', 'L3', '谭立云T1', 'T2', 'T3', 'T4', 'T5', 'T6', '王锦玲W1', 'W2', 'W3', 'RB', ''], 'chip_num_4': ['Cyto-12', 'R-徐耀权', 'W4', 'W5', 'W6', 'W7', '周玲丹Z1', 'Z2', 'Z3', 'Z4', 'Z5', 'Z6', 'RB', ''], 'chip_num_5': ['Karyomap', '甘小丽G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12', ''], 'X1 number': '203229580013', 'X2 number': '203229580014', 'X3 number': '203229580073', 'X4 number': '203189590151', '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'}

In [112]:
# 需要将chip_num_1 ~ chip_num_5 与芯片名匹配
# 需要将F-徐锦荣，柯奕K1， K2, ... -> [徐锦荣，柯奕, 柯奕, ...], [F, K1, K2, ...]
import re

class ChipInfoParser:
    def __init__(self, experiments):
        self.experiments = experiments
        self.chip_idx_dict = {"chip_num_1":"X1 number", "chip_num_2":"X2 number", "chip_num_4":"X3 number", "chip_num_5":"X4 number"}
        self.chip_info = {}
        self.name_dict ={}

    def parse_name(self, text):
        pattern = r'^([\u4e00-\u9fa5]+)([A-Z])?(\d{1,2})$'
        match = re.match(pattern, text)
        
        if match:
            chinese = match.group(1)
            initial = match.group(2) if match.group(2) else ''
            number = match.group(3)
            
            # 验证数字范围在1-20之间
            if 1 <= int(number) <= 20:
                return chinese, initial, number
    
        return None

    def parse_number(self, text):
        pattern = r'^([A-Z])(\d{1,2})$'
        match = re.match(pattern, text)
        
        if match:
            initial = match.group(1)
            number = match.group(2) if match.group(2) else ''
            
            # 验证数字范围在1-20之间
            if 2 <= int(number) <= 20:
                return initial, number
        
        return None

    def parse(self, experiments:dict):
        chip_infos = []
        name_dict ={}
        experiment_info = {}
        for key, value in experiments.items():
            chip_info = {}
            if key  in self.chip_idx_dict.keys():
                chip_info["type"] = value[0]
                chip_info["sample"] = value[1:-1]

                names = []
                name_numbers = []
                for name in chip_info["sample"]:
                    if "-" in name:
                        person_name = name.split("-")[1]
                        id_prefix = name.split("-")[0]
                        names.append(person_name)
                        name_numbers.append(id_prefix)
                    elif self.parse_name(name):
                        chinese, initial, number = self.parse_name(name)
                        name_dict[initial] = chinese
                        names.append(chinese)
                        name_numbers.append(number)
                    elif self.parse_number(name):
                        initial, number = self.parse_number(name)
                        names.append(name_dict[initial])
                        name_numbers.append(number)
                    elif "RB" == name:
                        person_name = "RB"
                        id_prefix = "1"
                        names.append(person_name)
                        name_numbers.append(id_prefix)
                    else:
                        raise ValueError(f"无法解析的名字: {name}")

                    if person_name not in name_dict:
                        name_dict[person_name] = []

                    name_dict[person_name].append(id_prefix)
                
                chip_info["names"] = names
                chip_info["name_numbers"] = name_numbers

                if self.chip_idx_dict[key] in experiments:
                    chip_info["idx"] = experiments[self.chip_idx_dict[key]]
                else:
                    raise ValueError(f"缺少芯片编号信息: {self.chip_idx_dict[key]}")
                
                if len(chip_info["names"]) == len(chip_info["name_numbers"]) == 12:
                    chip_infos.append(chip_info)
                else:
                    raise ValueError(f"样本数量不匹配 or !=12: names({len(chip_info['names'])}), name_numbers({len(chip_info['name_numbers'])})")
            
            elif key in self.chip_idx_dict.values():
                continue
            else:
                experiment_info[key] = value

        for key, value in experiment_info.items():
            for chip_info in chip_infos:
                chip_info[key] = value

        return chip_infos
    
parser = ChipInfoParser(experiments[0])
chip_infos = parser.parse(experiments[0])
for info in chip_infos:
    print(info)

{'type': 'Cyto-12', 'sample': ['F-徐锦荣', '柯奕K1', 'K2', 'K3', 'K4', 'K5', 'K6', 'K7', 'K8', 'K9', '梁健美L2', 'RB'], 'names': ['徐锦荣', '柯奕', '柯奕', '柯奕', '柯奕', '柯奕', '柯奕', '柯奕', '柯奕', '柯奕', '梁健美', 'RB'], 'name_numbers': ['F', '1', '2', '3', '4', '5', '6', '7', '8', '9', '2', '1'], 'idx': '203229580013', '实验时间': '2019年3月28日', '数据分析': '郭婧', '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'}
{'type': 'Cyto-12', 'sample': ['M-罗丽贞', 'L3', '谭立云T1', 'T2', 'T3', 'T4', 'T5', 'T6', '王锦玲W1', 'W2', 'W3', 'RB'], 'names': ['罗丽贞', '梁健美', '谭立云', '谭立云', '谭立云', '谭立云', '谭立云', '谭立云', '王锦玲', '王锦玲', '王锦玲', 'RB'], 'name_numbers': ['M', '3', '1', '2', '3', '4', '5', '6', '1', '2', '3', '1'], 'idx': '203229580014', '实验时间': '2019年3月28日', '数据分析': '郭婧', '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'}
{'type': 'Cyto-12', 'sample': ['R-徐耀权', 'W4', 'W5', 'W6', 'W7', '周玲丹Z1', 'Z2', 'Z3', 'Z4', 'Z5', 'Z6', 'RB'], 'names': ['徐耀权', '王锦玲', '王锦玲', '王锦玲', '王锦玲', '周玲丹', '周玲丹', '周玲丹', '周玲丹', '周玲丹', '周玲丹', 'RB'], 'name_numbers': ['R', '4', '5', '6', '7', '1', '2', '3', '4', '5', '6', '1'], 'idx': '203229580073', '实验时间': '2019年3月28日', '数据分析': '郭婧', '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'}
{'type': 'Karyomap', 'sample': ['甘小丽G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12'], 'names': ['甘小丽', '甘小丽', '甘小丽', '甘小丽', '甘小丽', '甘小丽', '甘小丽', '甘小丽', '甘小丽', '甘小丽', '甘小丽', '甘小丽'], 'name_numbers': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], 'idx': '203189590151', '实验时间': '2019年3月28日', '数据分析': '郭婧', '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'}

In [100]:
experiments

[{'实验时间': '2019年3月28日',
  '数据分析': '郭婧',
  'chip_num_1': ['Cyto-12',
   'F-徐锦荣',
   '柯奕K1',
   'K2',
   'K3',
   'K4',
   'K5',
   'K6',
   'K7',
   'K8',
   'K9',
   '梁健美L2',
   'RB',
   ''],
  'chip_num_2': ['Cyto-12',
   'M-罗丽贞',
   'L3',
   '谭立云T1',
   'T2',
   'T3',
   'T4',
   'T5',
   'T6',
   '王锦玲W1',
   'W2',
   'W3',
   'RB',
   ''],
  'chip_num_4': ['Cyto-12',
   'R-徐耀权',
   'W4',
   'W5',
   'W6',
   'W7',
   '周玲丹Z1',
   'Z2',
   'Z3',
   'Z4',
   'Z5',
   'Z6',
   'RB',
   ''],
  'chip_num_5': ['Karyomap',
   '甘小丽G1',
   'G2',
   'G3',
   'G4',
   'G5',
   'G6',
   'G7',
   'G8',
   'G9',
   'G10',
   'G11',
   'G12',
   ''],
  'X1 number': '203229580013',
  'X2 number': '203229580014',
  'X3 number': '203229580073',
  'X4 number': '203189590151',
  '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'},
 {'实验时间': '2019年4月1日',
  '数据分析': '潘家富',
  'chip_num_1': ['Cyto-12',
   'M-谢彩秀',
   '谢彩秀X1',
   'X2',
   'X3',
   'X4',
   'X5',
   'X6',
   'X7',
   'X8',
   'X9',
   'X10',
   'RB',
   ''],
  'chip_num_2': ['Cyto-12',
   'F-顾欣',
   'M-郑黛洁',
   '刘秋明L1',
   'L2',
   'L3',
   'L4',
   'L5',
   'L6',
   'L7',
   'L8',
   'L9',
   'RB',
   ''],
  'chip_num_4': ['Karyomap',
   'F-刘丙省',
   'M-谢彩霞',
   'R-刘启越',
   '熊婷婷X1',
   'X2',
   'X3',
   'X4',
   'X5',
   'X6',
   'X7',
   'X8',
   'X9',
   ''],
  'chip_num_5': ['Karyomap',
   'X10',
   'X11',
   '谭国妹T1',
   'T2',
   'T3',
   'T4',
   'T5',
   'T6',
   'T7',
   'T8',
   'T9',
   'T10',
   ''],
  'X1 number': '203229580045',
  'X2 number': '203229580051',
  'X3 number': '203189590083',
  'X4 number': '203189590084',
  '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'},
 {'实验时间': '2019年4月3日',
  '数据分析': '郭婧',
  'chip_num_1': ['Cyto-12',
   'F-余有栋',
   '童焕英T1',
   'T2',
   'T3',
   'T4',
   'T5',
   'T6',
   'T7',
   'T8',
   'T9',
   'T10',
   'RB',
   ''],
  'chip_num_2': ['Cyto-12',
   'R-温善荣',
   'T11',
   'T12',
   'T13',
   'T14',
   'T15',
   'T16',
   '李笑玲B  L1',
   'L2',
   'L3        （未完）',
   '刘美L4（重上）',
   'RB',
   ''],
  'chip_num_4': ['Karyomap',
   'F-韦学力',
   'R-韦承辉',
   '韦礼娜W1',
   'W2',
   'W3',
   'W4',
   'W5',
   'W6',
   'W7',
   'W8',
   'W9',
   'W10',
   ''],
  'chip_num_5': ['Karyomap (预实验)',
   'F-李红军',
   'M-刘莉',
   'R-刘基雄',
   'F-钟鑫',
   'M-黄娜',
   'R-李利芬',
   'F-梁献涛',
   'M-梁翠艳',
   'R-梁展彤',
   'F-黄锐斌',
   'M-周诗敏',
   'R-胎儿DNA',
   ''],
  'X1 number': '203229580101',
  'X2 number': '203229580106',
  'X3 number': '203189590057',
  'X4 number': '203189590070',
  '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'},
 {'实验时间': '2019年4月8日',
  '数据分析': '潘家富',
  'chip_num_1': ['Cyto-12',
   'F-陈朝源',
   '赵小兰Z1',
   'Z2',
   'Z3',
   'Z4',
   'Z5',
   'Z6',
   'Z7',
   'Z8',
   '石成梅S1',
   'S2',
   'RB',
   ''],
  'chip_num_2': ['Cyto-12',
   'M-柯奕',
   'S3',
   'S4',
   'S5',
   'S6',
   'S7',
   'S8',
   '吴小玲C   W1',
   'W2',
   'W3',
   'W4',
   'RB',
   ''],
  'chip_num_4': ['Karyomap',
   'F-秦望',
   'M-周小娜',
   'R-秦可馨',
   'F-刘佐帆',
   'M-苏新姬',
   'R-刘峻均',
   '邱洁红Q1',
   'Q2',
   'Q3',
   'Q4',
   'Q5',
   'Q6',
   ''],
  'chip_num_5': ['Karyomap',
   'Q7',
   'Q8',
   'Q9',
   'Q10',
   'Q11',
   '黄晓连H1',
   'H2',
   'H3',
   'H4',
   'H5',
   'H6',
   'H7',
   ''],
  'X1 number': '203229580118',
  'X2 number': '203229580119',
  'X3 number': '203392440040',
  'X4 number': '203392440050',
  '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'},
 {'实验时间': '2019年4月10日',
  '数据分析': '郭婧',
  'chip_num_1': ['Cyto-12',
   'F-周志军',
   '廖海婷L1',
   'L2',
   'L3',
   'L4',
   'L5',
   'L6',
   'L7',
   'L8',
   'L9',
   'L10',
   'RB',
   ''],
  'chip_num_2': ['Cyto-12',
   'M-李笑玲',
   'L11',
   'L12',
   'L13',
   '黄桂梅B   H1',
   'H2',
   'H3',
   'H4',
   'H5',
   'H6',
   'H7',
   'RB',
   ''],
  'chip_num_4': ['Cyto-12',
   'R-区碧兰',
   '李笑玲B   L4',
   'L5',
   'L6',
   'L7',
   'L8',
   '郭梅如G1',
   'G2',
   'G3',
   'G4',
   'G5',
   'RB',
   ''],
  'chip_num_5': ['Karyomap',
   'M-韩璇',
   '周小娜Z1',
   'Z2',
   'Z3',
   'Z4',
   'Z5',
   'Z6',
   'Z7',
   'Z8',
   'Z9',
   'Z10',
   'Z11',
   ''],
  'X1 number': '203229580005',
  'X2 number': '203229580043',
  'X3 number': '203229580104',
  'X4 number': '203189590128',
  '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'},
 {'实验时间': '2019年4月14日',
  '数据分析': '潘家富',
  'chip_num_1': ['Cyto-12',
   'F-杨建军',
   '李敏U   L1',
   'L2',
   'L3',
   'L4',
   'L5',
   'L6',
   'L7',
   'L8',
   'L9',
   'L10',
   'RB',
   ''],
  'chip_num_2': ['Cyto-12',
   'M-赵小兰',
   'L11',
   'L12',
   'L13',
   '刘海玲B   L1',
   'L2',
   'L3',
   'L4',
   'L5',
   'L6',
   'L7',
   'RB',
   ''],
  'chip_num_4': ['Cyto-12',
   'R-杨先俊',
   'L8',
   'L9',
   '樊建红F1',
   'F2',
   'F3',
   'F4',
   'F5',
   'F6',
   'F7',
   'F8',
   'RB',
   ''],
  'chip_num_5': ['Cyto-12',
   'M-李敏',
   'F9',
   'F10',
   'F11',
   'F12',
   '曾梅珍Z1',
   'Z2',
   'Z3',
   'Z4',
   'Z5',
   'Z6',
   'RB',
   ''],
  'X1 number': '203218670043',
  'X2 number': '203218670072',
  'X3 number': '203218670077',
  'X4 number': '203218670091',
  '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'},
 {'实验时间': '2019年4月16日',
  '数据分析': '郭婧',
  'chip_num_1': ['Cyto-12',
   'F-黄敏',
   '劳美琼L1',
   'L2',
   'L3',
   'L4',
   '贺桂萍H1',
   'H2',
   'H3',
   'H4',
   'H5',
   'H6',
   'RB',
   ''],
  'chip_num_2': ['Cyto-12',
   'R-李德建',
   '吴春云W1',
   'W2',
   'W3',
   'W4',
   'W5',
   'W6',
   '林紫菊L1',
   'L2',
   'L3',
   'L4',
   'RB',
   ''],
  'chip_num_4': ['Karyomap',
   'F-彭欢',
   'M-陈丽珠(预实验)',
   'R-彭梓睿',
   'F-黄予洋',
   'M-李宁馥(预实验)',
   'R-李呈杰',
   'F-刘景福',
   'M-卢妙龄(预实验)',
   'R-刘如峻',
   '谢彩霞X1',
   'X2',
   'X3',
   ''],
  'chip_num_5': ['Karyomap',
   'X4',
   'X5',
   'X6',
   'X7',
   'X8',
   'X9',
   'X10',
   'X11',
   'X12',
   'X13',
   'X14',
   'X15',
   ''],
  'X1 number': '203225130029',
  'X2 number': '203225130034',
  'X3 number': '203388160111',
  'X4 number': '203388160067',
  '备注': '红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'},
 {'实验时间': '2019年4月18日',
  '数据分析': '潘家富',
  'chip_num_1': ['Cyto-12',
   'F-杨尊才',
   '黎巧娟L1',
   'L2',
   'L3',
   'L5',
   '颜绵秋Y1',
   'Y2',
   'Y3',
   'Y4',
   'Y5',
   'Y6',
   'RB',
   ''],
  'chip_num_2': ['Cyto-12',
   'M-刘秋明',
   '何妹H1',
   'H2',
   'H3',
   '陈小佳B  C1',
   'C2',
   'C3',
   'C4',
   'C5',
   'C6',
   'C7',
   'RB',
   ''],
  'chip_num_4': ['Cyto-12',
   'R-杨佳颖',
   '赵琴Z1',
   'Z2',
   'Z3',
   'Z4',
   'Z5',
   'Z6',
   'Z7',
   'Z8',
   'Z9',
   '刘慕贤L1',
   'RB',
   ''],
  'chip_num_5': ['Cyto-12',
   'M-廖海婷',
   'L2',
   'L3',
   'L4',
   'L5',
   'L6',
   'L7',
   'L8',
   'L9',
   'L10',
   'L11',
   'RB',
   ''],
  'X1 number': '203229580018',
  'X2 number': '203229580052',
  'X3 number': '203229580060',
  'X4 number': '203229580103',
  '备注': '红色字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'},
 {'实验时间': '2019年4月22日',
  '数据分析': '郭婧',
  'chip_num_1': ['Cyto-12',
   'F-邹师荣',
   '杨蕾Y1',
   'Y2',
   'Y3',
   'Y4',
   'Y5',
   'Y6',
   'Y7',
   'Y8',
   'Y9',
   '覃潍潍Q1',
   'RB',
   ''],
  'chip_num_2': ['Cyto-12',
   'M-刘海玲',
   'Q2',
   'Q3',
   '陈婉B    C1',
   'C2',
   'C3',
   'C4',
   'C5',
   'C6',
   'C7',
   'C8',
   'RB',
   ''],
  'chip_num_4': ['Cyto-12',
   'R-邹悦',
   'C9',
   'C10',
   'C11',
   'C12',
   'C13',
   'C14',
   'C15',
   'C16',
   'C17',
   'C18',
   'RB',
   ''],
  'chip_num_5': ['Karyomap',
   'R-李宁馥绒毛DNA',
   'F-何龙',
   'F-龚建兵',
   'M-周小风',
   'R-周小风儿子',
   '周小风Z1',
   'Z2',
   'Z3',
   'Z4',
   'Z5',
   'Z6',
   'Z7',
   ''],
  'X1 number': '203203230020',
  'X2 number': '203203230027',
  'X3 number': '203203230037',
  'X4 number': '203189590156',
  '备注': '红色字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特殊备注则为同一家系外周血：F表示父亲，M-母亲，R-先证者'}]

In [114]:
import re

def parse_name(text):
    # 匹配中文（可能包含英文字母），然后大写字母，最后数字1-20
    pattern = r'^([\u4e00-\u9fa5A-Z]+)\s*([A-Z])\s*(\d{1,2})$'
    match = re.match(pattern, text)
    
    if match:
        chinese_part = match.group(1)
        initial = match.group(2)
        number = match.group(3)
        
        # 验证数字范围在1-20之间
        if 1 <= int(number) <= 20:
            return chinese_part, initial, number
    
    return None

# 测试
test_cases = [
    "柯奕K1", 
    "李笑玲B  L1", 
    "张三A5", 
    "王五B15", 
    "赵六20", 
    "测试C25",
    "无效输入"
]

for case in test_cases:
    result = parse_name(case)
    if result:
        print(f"'{case}' -> {result}")
    else:
        print(f"'{case}' -> 不匹配")

'柯奕K1' -> ('柯奕', 'K', '1')
'李笑玲B  L1' -> ('李笑玲B', 'L', '1')
'张三A5' -> ('张三', 'A', '5')
'王五B15' -> ('王五', 'B', '15')
'赵六20' -> 不匹配
'测试C25' -> 不匹配
'无效输入' -> 不匹配

## 读取非结构化的JSON数据

In [118]:
import pandas as pd
import json

json_path=r"D:\03.projects\AI.PGT\snparray_analysis\data\experiment_snparray.json"

with open(json_path, 'r', encoding='utf-8') as f:
    experiments = json.load(f)

# 查看数据
experiments[0]
df_experiments = pd.DataFrame(experiments)
df_experiments.head()

,type,sample,names,name_numbers,idx,实验时间,数据分析,备注
0,Cyto-12,"[F-徐锦荣, 柯奕K1, K2, K3, K4, K5, K6, K7, K8, K9, ...","[徐锦荣, 柯奕, 柯奕, 柯奕, 柯奕, 柯奕, 柯奕, 柯奕, 柯奕, 柯奕, 梁健美,...","[F, 1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 1]",203229580013,2019年3月28日,郭婧,红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特...
1,Cyto-12,"[M-罗丽贞, L3, 谭立云T1, T2, T3, T4, T5, T6, 王锦玲W1, ...","[罗丽贞, 梁健美, 谭立云, 谭立云, 谭立云, 谭立云, 谭立云, 谭立云, 王锦玲, ...","[M, 3, 1, 2, 3, 4, 5, 6, 1, 2, 3, 1]",203229580014,2019年3月28日,郭婧,红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特...
2,Cyto-12,"[R-徐耀权, W4, W5, W6, W7, 周玲丹Z1, Z2, Z3, Z4, Z5,...","[徐耀权, 王锦玲, 王锦玲, 王锦玲, 王锦玲, 周玲丹, 周玲丹, 周玲丹, 周玲丹, ...","[R, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 1]",203229580073,2019年3月28日,郭婧,红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特...
3,Karyomap,"[甘小丽G1, G2, G3, G4, G5, G6, G7, G8, G9, G10, G...","[甘小丽, 甘小丽, 甘小丽, 甘小丽, 甘小丽, 甘小丽, 甘小丽, 甘小丽, 甘小丽, ...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",203189590151,2019年3月28日,郭婧,红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特...
4,Cyto-12,"[M-谢彩秀, 谢彩秀X1, X2, X3, X4, X5, X6, X7, X8, X9,...","[谢彩秀, 谢彩秀, 谢彩秀, 谢彩秀, 谢彩秀, 谢彩秀, 谢彩秀, 谢彩秀, 谢彩秀, ...","[M, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]",203229580045,2019年4月1日,潘家富,红色加粗字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无特...

In [124]:
# 需要将该表格的chipid和临床样本进行匹配
clinical_path = r"D:\03.projects\AI.PGT\snparray_analysis\data\clinical_data_demo.csv"
df_clinical = pd.read_csv(clinical_path, sep=",")
# df_clinical.head()
df_clinical[["女方姓名","病历号", "PGD/PGS编号", "活检胚胎总数"]].head()

  女方姓名    病历号  PGD/PGS编号  活检胚胎总数
0  彭晶晶  37483          1      12
1  彭晶晶  37483          2      12
2  彭晶晶  37483          3      12
3  彭晶晶  37483          4      12
4  彭晶晶  37483          9      12

In [ ]:
# 读取多个excel文件，并合并
import pandas as pd

excel_path = r"D:\01.data\01.gene\ChipData\experiment_record\5.芯片实验记录表2020.12.29（勿删）.xlsx"
df_list = pd.read_excel(excel_path, sheet_name=None, header=None)
print(df_list.keys())

Index(['type', 'idx', '实验时间', '数据分析', 'chip_sub_idx', '女方姓名', 'PGD/PGS编号',
       'sample'],
      dtype='object')

In [ ]:
df = pd.concat(df_list.values(), ignore_index=True)
df
# df_list.values()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,芯片实验记录表,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,实验时间： 2019 年 3 月 28 日,NaN,NaN,NaN,NaN,NaN,数据分析：郭婧,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cyto-12,F-徐锦荣,柯奕K1,K2,K3,K4,K5,K6,K7,K8,K9,梁健美L2,RB,NaN,NaN
3,Cyto-12,M-罗丽贞,L3,谭立云T1,T2,T3,T4,T5,T6,王锦玲W1,W2,W3,RB,NaN,NaN
4,NaN,R01C01,R02C01,R03C01,R04C01,R05C01,R06C01,R01C02,R02C02,R03C02,R04C02,R05C02,R06C02,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2545,Karyomap,F-方慧,M-周海兰(预实验),R-吕桂玉,F-魏志诚,M-曾丽兰(预实验),R-魏伊依,丘兰兰Q1,Q2,Q3,Q4,Q5,周诗敏Z1,NaN,NaN
2546,NaN,X1 number：204289520017 ...,NaN,NaN,NaN,NaN,NaN,X2 number：204270360032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2547,NaN,X3 number：204270360069 ...,NaN,NaN,NaN,NaN,NaN,X4 number：204694750147,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2548,备注：红色字体表示需要区分正常和携带；Cyto-12芯片中R01C01为阳性对照外周血，如无...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2549,标绿背景的病人表示按新收费标准,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
### 读取experiment和clinical的数据表，将snp id和clinical id合并

import pandas as pd

snparray_path = r"D:\03.projects\AI.PGT\snparray_analysis\data\5.芯片实验记录表2020.12.29_persons.csv"
clinical_path = r"D:\03.projects\AI.PGT\snparray_analysis\data\clinical_data_pgt.csv"
df_snparray = pd.read_csv(snparray_path,header=0)
print(df_snparray.head())

df_clinical = pd.read_csv(clinical_path,header=1)
print(df_clinical.head())

# 创建一个新的列，将女方姓名和PGD/PGS编号合并 彭晶晶-1

      type           idx        实验时间 数据分析 chip_sub_idx 女方姓名 PGD/PGS编号 sample
0  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R01C01  徐锦荣         F  F-徐锦荣
1  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R02C01   柯奕         1   柯奕K1
2  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R03C01   柯奕         2     K2
3  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R04C01   柯奕         3     K3
4  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R05C01   柯奕         4     K4
     病历号       统计日期      周期号 女方姓名  女方年龄 男方姓名  男方年龄  第几周期   周期类型          助孕方案  \
0  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR
1  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR
2  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR
3  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR
4  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR

   ... D6滋养层 D7分期 D7内细胞团 D7滋养层 诊断不可移植 是否推荐移植       排序字段   p_id    o_id  E_IDNo
0  ...   NaN  NaN    NaN   NaN      否      是  2019/6/11  58412  107842  554274
1  ...   NaN  NaN    NaN   NaN      是      否  2019/6/11  58412  107842  554278
2  ...   NaN  NaN    NaN   NaN      是      否  2019/6/11  58412  107842  554279
3  ...   NaN  NaN    NaN   NaN      是      否  2019/6/11  58412  107842  554280
4  ...   NaN  NaN    NaN   NaN      否      是  2019/6/11  58412  107842  554281

[5 rows x 75 columns]

In [ ]:
# add new col
df_snparray['女方姓名-PGD/PGS编号'] = df_snparray.apply(lambda row: f"{row['女方姓名']}-{row['PGD/PGS编号']}", axis=1)
print(df_snparray.head())

df_clinical['女方姓名-PGD/PGS编号'] = df_clinical.apply(lambda row: f"{row['女方姓名']}-{row['PGD/PGS编号']}", axis=1)
print(df_clinical.head())

      type           idx        实验时间 数据分析 chip_sub_idx 女方姓名 PGD/PGS编号 sample  \
0  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R01C01  徐锦荣         F  F-徐锦荣
1  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R02C01   柯奕         1   柯奕K1
2  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R03C01   柯奕         2     K2
3  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R04C01   柯奕         3     K3
4  Cyto-12  2.032296e+11  2019年3月28日   郭婧       R05C01   柯奕         4     K4

  女方姓名-PGD/PGS编号
0          徐锦荣-F
1           柯奕-1
2           柯奕-2
3           柯奕-3
4           柯奕-4
     病历号       统计日期      周期号 女方姓名  女方年龄 男方姓名  男方年龄  第几周期   周期类型          助孕方案  \
0  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR
1  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR
2  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR
3  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR
4  37483  2019/6/11  1057662  彭晶晶    25   李勇    28     2  新鲜加解冻  PGT_A+PGT_SR

   ... D7分期 D7内细胞团 D7滋养层 诊断不可移植 是否推荐移植       排序字段   p_id    o_id  E_IDNo  \
0  ...  NaN    NaN   NaN      否      是  2019/6/11  58412  107842  554274
1  ...  NaN    NaN   NaN      是      否  2019/6/11  58412  107842  554278
2  ...  NaN    NaN   NaN      是      否  2019/6/11  58412  107842  554279
3  ...  NaN    NaN   NaN      是      否  2019/6/11  58412  107842  554280
4  ...  NaN    NaN   NaN      否      是  2019/6/11  58412  107842  554281

  女方姓名-PGD/PGS编号
0          彭晶晶-1
1          彭晶晶-2
2          彭晶晶-3
3          彭晶晶-4
4          彭晶晶-9

[5 rows x 76 columns]

In [12]:
# merge 
merged_inner = pd.merge(df_clinical, df_snparray, on='女方姓名-PGD/PGS编号', how='inner')
print(merged_inner.head())
print(merged_inner.shape)

     病历号       统计日期      周期号 女方姓名_x  女方年龄 男方姓名  男方年龄  第几周期   周期类型  \
0  37483  2019/6/11  1057662    彭晶晶    25   李勇    28     2  新鲜加解冻
1  37483  2019/6/11  1057662    彭晶晶    25   李勇    28     2  新鲜加解冻
2  37483  2019/6/11  1057662    彭晶晶    25   李勇    28     2  新鲜加解冻
3  37483  2019/6/11  1057662    彭晶晶    25   李勇    28     2  新鲜加解冻
4  37483  2019/6/11  1057662    彭晶晶    25   李勇    28     2  新鲜加解冻

           助孕方案  ...  E_IDNo 女方姓名-PGD/PGS编号     type           idx  \
0  PGT_A+PGT_SR  ...  554274          彭晶晶-1  Cyto-12  2.033687e+11
1  PGT_A+PGT_SR  ...  554278          彭晶晶-2  Cyto-12  2.033687e+11
2  PGT_A+PGT_SR  ...  554279          彭晶晶-3  Cyto-12  2.033687e+11
3  PGT_A+PGT_SR  ...  554280          彭晶晶-4  Cyto-12  2.033687e+11
4  PGT_A+PGT_SR  ...  554281          彭晶晶-9  Cyto-12  2.033687e+11

         实验时间 数据分析 chip_sub_idx 女方姓名_y PGD/PGS编号_y sample
0  2019年6月24日   李荣       R02C01    彭晶晶           1  彭晶晶P1
1  2019年6月24日   李荣       R03C01    彭晶晶           2     P2
2  2019年6月24日   李荣       R04C01    彭晶晶           3     P3
3  2019年6月24日   李荣       R05C01    彭晶晶           4     P4
4  2019年6月24日   李荣       R04C02    彭晶晶           9     P9

[5 rows x 84 columns]
(1130, 84)